spring:
  profiles:
    include:
      - ai
      - member
      - discord
      - database

management:
  server:
    port: 9090

logging:
  level:
    root: info
    com.zaxxer.hikari.pool.HikariPool: info
    exposed: debug

dev:
  kuro9:
    jwt:
      key: test123
    webhook:
      url: ${DISCORD_ERROR_WEBHOOK}