services:
  app:
    container_name: app-homepage-backend
    image: app-homepage-backend
    env_file:
      - ${ENV_FILE_LOC}
    networks:
      - database

networks:
  database:
    external: true
