spring:
  profiles:
    include:
      - member
      - database
      - smartapp-webhook
      - redis
dev:
  kuro9:
    discord:
      api:
        token: ${DISCORD_TOKEN}
    cookie:
      redirect-front-uri: https://kuro9.dev
      domain: kuro9.dev
      secure: true

---
# dev env
spring:
  config:
    activate:
      on-profile: dev
dev:
  kuro9:
    cookie:
      redirect-front-uri: http://localhost:8090
      domain: localhost
      secure: false

