name: front-homepage.yml

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REMOTE_BASE_DIR: "/var/services/homes/github-cd/frontend-homepage"
      REMOTE_TARGET_DIR: "/var/services/homes/github-cd/frontend-homepage/pages/kuro9-dev"
    environment: APP_HOMEPAGE_BACKEND

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Frontend
        run: ./gradlew :module-front:application:app-homepage:jsBrowserDistribution -Dmode=prod

      - name: Archive Frontend Files
        run: |
          cd module-front/application/app-homepage/build/dist/js/productionExecutable
          tar -czf /tmp/frontend.tar.gz .

      - name: Copy Frontend Archive to Remote Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}

          source: "module-front/application/app-homepage/build/dist/js/productionExecutable/tmp/frontend.tar.gz"
          target: "${{ env.REMOTE_BASE_DIR }}"

          overwrite: true

      - name: Deploy Frontend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}

          script: |
            set -e

            mkdir -p ${{ env.REMOTE_TARGET_DIR }}

            rm -rf ${{ env.REMOTE_TARGET_DIR }}/*

            tar -xzf ${{ env.REMOTE_BASE_DIR }}/frontend.tar.gz \
              -C ${{ env.REMOTE_TARGET_DIR }}

            rm ${{ env.REMOTE_BASE_DIR }}/frontend.tar.gz

            /usr/local/bin/docker exec nginx-kuro9-main nginx -t
            /usr/local/bin/docker exec nginx-kuro9-main nginx -s reload